# Generated by Django 5.2.6 on 2025-10-07 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("pending", "Pending"),
                            ("to_be_deleted", "To Be Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "highest_risk_category",
                    models.CharField(
                        choices=[
                            ("appropriate", "Appropriate"),
                            ("sexual", "Sexual"),
                            ("hate", "Hate"),
                            ("harassment", "Harassment"),
                            ("self-harm", "Self-Harm"),
                            ("sexual/minors", "Sexual/Minors"),
                            ("hate/threatening", "Hate/Threatening"),
                            ("violence/graphic", "Violence/Graphic"),
                            ("self-harm/intent", "Self-Harm/Intent"),
                            ("self-harm/instructions", "Self-Harm/Instructions"),
                            ("harassment/threatening", "Harassment/Threatening"),
                            ("violence", "Violence"),
                            ("spam", "Spam"),
                        ],
                        default="appropriate",
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("moderation_data_full", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
