# Generated by Django 5.2.6 on 2025-10-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="highest_risk_category",
            new_name="risk_category",
        ),
    ]
