# Generated by Django 5.2.6 on 2026-07-29 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_highest_risk_category_review_risk_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="risk_category",
            field=models.CharField(
                choices=[
                    ("appropriate", "Appropriate"),
                    ("unknown", "Unknown"),
                    ("sexual", "Sexual"),
                    ("hate", "Hate"),
                    ("harassment", "Harassment"),
                    ("self-harm", "Self-Harm"),
                    ("sexual/minors", "Sexual/Minors"),
                    ("hate/threatening", "Hate/Threatening"),
                    ("violence/graphic", "Violence/Graphic"),
                    ("self-harm/intent", "Self-Harm/Intent"),
                    ("self-harm/instructions", "Self-Harm/Instructions"),
                    ("harassment/threatening", "Harassment/Threatening"),
                    ("violence", "Violence"),
                    ("spam", "Spam"),
                ],
                default="appropriate",
                max_length=50,
            ),
        ),
    ]
